name: Provision with Terraform and Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'trading-bot-app-v2'
  PYTHON_VERSION: '3.12'

jobs:
  provision:
    runs-on: ubuntu-latest
    name: 🏗️ Provision Infrastructure with Terraform
    environment: prod 
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform Init'
        run: terraform init -input=false
        working-directory: ./terraform

      - name: 'Terraform Validate'
        run: terraform validate
        working-directory: ./terraform

      - name: 'Terraform Apply'
        env:
          TF_VAR_binance_api_key: ${{ secrets.BINANCE_API_KEY }}
          TF_VAR_binance_api_secret: ${{ secrets.BINANCE_API_SECRET }}
          TF_VAR_subscriptionId: ${{ vars.SUBSCRIPTION_ID }}
          TF_VAR_resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          TF_VAR_location: ${{ vars.LOCATION }}
          TF_VAR_applicationInsightsName: ${{ vars.APPLICATION_INSIGHTS_NAME }}
          TF_VAR_logAnalyticsName: ${{ vars.LOG_ANALYTICS_NAME }}
          TF_VAR_functionAppName: ${{ vars.FUNCTION_APP_NAME }}
          TF_VAR_functionPlanName: ${{ vars.FUNCTION_PLAN_NAME }}
          TF_VAR_storageAccountName: ${{ vars.STORAGE_ACCOUNT_NAME }}
          TF_VAR_maximumInstanceCount: ${{ vars.MAXIMUM_INSTANCE_COUNT }}
          TF_VAR_instanceMemoryMB: ${{ vars.INSTANCE_MEMORY_MB }}
          TF_VAR_functionAppRuntime: ${{ vars.FUNCTION_APP_RUNTIME }}
          TF_VAR_functionAppRuntimeVersion: ${{ vars.FUNCTION_APP_RUNTIME_VERSION }}
          TF_VAR_zoneRedundant: ${{ vars.ZONE_REDUNDANT }}
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform

  deploy:
    runs-on: ubuntu-latest
    name: 🚀 Deploy Function Code
    needs: provision
    environment: prod
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Setup Python Environment'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Install Dependencies and Package'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          zip -r deployment.zip . -x "terraform/*" ".git/*"

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: 'deployment.zip'