name: Provision with Terraform and Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'trading-bot-app-v2'
  PYTHON_VERSION: '3.12'

jobs:
  provision:
    runs-on: ubuntu-latest
    name: 🏗️ Provision Infrastructure with Terraform
    environment: prod 
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform Init'
        run: terraform init -input=false
        working-directory: ./terraform

      - name: 'Terraform Validate'
        run: terraform validate
        working-directory: ./terraform

      - name: 'Terraform Apply'
        # Pass the environment secret to the Terraform variable
        run: terraform apply -auto-approve -input=false \
          -var="binance_api_key=${{ secrets.BINANCE_API_KEY }}" \
          -var="binance_api_secret=${{ secrets.BINANCE_API_SECRET }}"
        working-directory: ./terraform

  deploy:
    runs-on: ubuntu-latest
    name: 🚀 Deploy Function Code
    needs: provision
    environment: prod
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Setup Python Environment'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Install Dependencies and Package'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          zip -r deployment.zip . -x "terraform/*" ".git/*"

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: 'deployment.zip'